[package]
name = "gpu_rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.12.3"
env_logger = "0.9.3"
futures-intrusive = "0.5.0"
log = "0.4.17"
pollster = "0.2.5"
wgpu = "0.14.0"
winit = "0.27.5"

